### ISSUE TITLE
Roadmap for 1.0

### ISSUE THREAD

**Issue by tilmanpotthof** [Gillespie59/eslint-plugin-angular#323]
We already have identified some tasks for 1.0 and I think it is worth to consider what we think is missing for a 1.0 release. Also, what quality requirements will we have after 1.0.

https://github.com/Gillespie59/eslint-plugin-angular/milestones/1.0.0

**Comment by remcohaszing** [comment]
I suggest to try and release `1.0.0` ASAP with the main focus on support for `eslint@^2.0.0`.

I think we should:
- Remove deprecated rules. (#298)
- Remove support for the old-style rules. (with the `ng_` prefix)
- Bump to `eslint@^2.0.0`. (#340)
- Disable all rules by default. (#258) In the new ESLint this is [no longer supported](http://eslint.org/docs/user-guide/migrating-to-2.0.0#plugins-no-longer-have-default-configurations) anyway.
- Validate everything still works manually. I don't thinks this needs to be a problem, since the test coverage is pretty decent.

The following issues are nice to have, but may be implemented in a later version as well:
- Revisit `angularRule` because of the [scope analysis changes](http://eslint.org/docs/user-guide/migrating-to-2.0.0#scope-analysis-changes).
- Create custom environments. (#331)

Should we create a `1.0` branch for this?

**Comment by Gillespie59** [comment]
:+1:  I am going to create the 1.0 branch

**Comment by Gillespie59** [comment]
Done  https://github.com/Gillespie59/eslint-plugin-angular/tree/1.0

**Comment by Gillespie59** [comment]
and the #322  ?

**Comment by Gillespie59** [comment]
I have created a new issue #341 for the old-syntax.

**Comment by Gillespie59** [comment]
I have updated the 1.0 branch to eslint 2.0 eveything looks fine. Can you send your PR again with all your change ?

**Comment by abdonrd** [comment]
+1 to ESLint 2.0! :+1:

**Comment by remcohaszing** [comment]
I don't think the one remaining issue for this roadmap should block a release. I think this is ready for merging + releasing.

**Comment by Gillespie59** [comment]
Can you prepare the release ?
- Update the version number in the 1.0.0 branch
- Merge to the dev branch
- Merge to the master branch
- Test if everythin is OK
- Delete the 1.0.0 branch

And I will publish the release on NPM and publish the GIT tag.

Thanks a lot.

Le mar. 23 févr. 2016 à 16:24, Remco Haszing <notifications@github.com> a
écrit :

**Comment by remcohaszing** [comment]
Alright, I'm on it! :+1:

**Comment by remcohaszing** [comment]
- [x] Update the version number in the 1.0.0 branch
- [x] Merge to the dev branch
- [x] Merge to the master branch
- [x] Test if everything is OK

  - Tested on a project I'm working on using `npm link`.
  - All that broke were the changed rules in ESLint's default ruleset.
  - Environments work. :smile_cat: 
- [ ] Delete the 1.0.0 branch

 - Didn't delete this branch yet, so you track everything I did.

I think it's ready for tagging + releasing.

**Comment by Gillespie59** [comment]
Done ! Thans a lot @remcohaszing ! will publish something on twitter
